### ISSUE TITLE
Request to Join as a Collaborator

### ISSUE THREAD

**Issue by revanthmahindra** [Neufal777/telegram-bot-mlh#1]
Hi, I'm Revanth from India. 
I'm really interested in contributing to your project.
Could you please consider adding me as a collaborator? I'm excited about the opportunity to contribute and learn.
Thank you for your consideration.

**Comment by GibzB** [comment]
Kindly go ahead to star the repo and @Neufal777 will invite you to collaborate. 

Cheers!

**Comment by Neufal777** [comment]
Hey @revanthmahindra , just added you
